[phases.setup]

[variables]
PYTHONUNBUFFERED = "1"


# .nixpacks/plan.toml
[phases.setup]
nixPkgs = [
"python38", "postgresql",
  "libGL",
  "glib",
  "xorg.libSM",
  "xorg.libXrender",
  "xorg.libXext",
  "mesa"
]

[phases.install]
cmds = ["python -m pip install --upgrade pip", "pip install -r requirements.txt"]

[start]
cmd = "gunicorn backend.wsgi:application"


FROM python:3.8-slim

# Install system dependencies for OpenCV
RUN apt-get update && apt-get install -y --no-install-recommends \
    libgl1-mesa-glx \
    libglib2.0-0 \
    libsm6 \
    libxrender1 \
    libxext6 \
    libx11-6 \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

# Set working directory
WORKDIR /app

# Copy requirements first for better caching
COPY requirements.txt .

# Install Python dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Copy project files
COPY . .

# Start command
CMD gunicorn backend.wsgi:application