[phases.setup]

[variables]
PYTHONUNBUFFERED = "1"


# .nixpacks/plan.toml
[phases.setup]
nixPkgs = [
"python38", "postgresql",
  "libGL",
  "glib",
  "xorg.libSM",
  "xorg.libXrender",
  "xorg.libXext",
  "mesa"
]

[phases.install]
cmds = ["python -m pip install --upgrade pip", "pip install -r requirements.txt"]

[start]
cmd = "gunicorn backend.wsgi:application"