# railway.toml
[build]
builder = "nixpacks"
buildCommand = "pip install -r requirements.txt"

[deploy]
startCommand = "gunicorn backend.wsgi:application"
healthcheckPath = "/"
healthcheckTimeout = 100