# Generated by Django 5.1.4 on 2025-02-13 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_rename_candidate_id_candidatetable_candidate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidatetable',
            name='profile_image',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='candidatetable',
            name='candidate_cv',
            field=models.URLField(),
        ),
    ]
