# Generated by Django 5.1.4 on 2025-04-12 13:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_candidatetable_profile_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidatetable',
            name='about',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='candidatetable',
            name='bio',
            field=models.TextField(default=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='candidatetable',
            name='contact_information',
            field=models.JSONField(default='2'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='candidatetable',
            name='education',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='candidatetable',
            name='experience',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='candidatetable',
            name='location',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='candidatetable',
            name='professional_links',
            field=models.JSONField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='candidatetable',
            name='resume',
            field=models.FileField(default=1, upload_to='resumes/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='candidatetable',
            name='skills',
            field=models.JSONField(default=1),
            preserve_default=False,
        ),
    ]
