# Generated by Django 5.1.4 on 2025-04-12 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_candidatetable_about_candidatetable_bio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruitertable',
            name='about',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recruitertable',
            name='bio',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recruitertable',
            name='company_information',
            field=models.JSONField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recruitertable',
            name='contact_information',
            field=models.JSONField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recruitertable',
            name='location',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recruitertable',
            name='profile_image',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
    ]
