# Generated by Django 5.1.4 on 2025-04-12 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_recruitertable_about_recruitertable_bio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidatetable',
            name='about',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='candidatetable',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='candidatetable',
            name='candidate_cv',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='candidatetable',
            name='contact_information',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='candidatetable',
            name='education',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='candidatetable',
            name='experience',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='candidatetable',
            name='location',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='candidatetable',
            name='professional_links',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='candidatetable',
            name='profile_image',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='candidatetable',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to='resumes/'),
        ),
        migrations.AlterField(
            model_name='candidatetable',
            name='skills',
            field=models.JSONField(default=list),
        ),
    ]
