# Generated by Django 5.1.4 on 2025-05-09 12:51

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_alter_candidatetable_about_alter_candidatetable_bio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidatetable',
            name='resume',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='resume'),
        ),
    ]
