# Generated by Django 5.1.4 on 2025-05-09 13:00

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_alter_candidatetable_resume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidatetable',
            name='candidate_cv',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='resume'),
        ),
        migrations.AlterField(
            model_name='candidatetable',
            name='profile_image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='profile_image'),
        ),
        migrations.AlterField(
            model_name='recruitertable',
            name='profile_image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='profile_image'),
        ),
    ]
