# Generated by Django 5.1.3 on 2024-12-20 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_posting', '0004_rename_job_id_applicationtable_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpostingtable',
            name='is_private',
            field=models.BooleanField(default=False),
        ),
    ]
