# Generated by Django 5.1.3 on 2024-12-24 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_posting', '0005_jobpostingtable_is_private'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationtable',
            name='marks',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
