# Generated by Django 5.1.3 on 2024-12-24 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_posting', '0006_alter_applicationtable_marks'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationtable',
            name='interview_status',
            field=models.BooleanField(default=False),
        ),
    ]
