# Generated by Django 5.1.3 on 2024-12-27 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_posting', '0007_applicationtable_interview_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationtable',
            name='application_status',
            field=models.CharField(choices=[('Under Review', 'Under Review'), ('Selected', 'Selected'), ('Rejected', 'Rejected')], default='Not Applied', max_length=20),
        ),
    ]
