# Generated by Django 5.1.3 on 2024-12-27 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_posting', '0008_applicationtable_application_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationtable',
            name='application_status',
            field=models.CharField(choices=[('Under Review', 'Under Review'), ('Selected', 'Selected'), ('Rejected', 'Rejected')], default='Under Review', max_length=20),
        ),
    ]
