# Generated by Django 5.1.4 on 2025-01-13 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_rename_candidate_id_candidatetable_candidate_and_more'),
        ('job_posting', '0009_alter_applicationtable_application_status'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='applicationtable',
            unique_together={('job', 'candidate')},
        ),
    ]
