# Generated by Django 5.1.4 on 2025-02-14 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_posting', '0011_applicationtable_interview_frames'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationtable',
            name='interview_frames',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
