# Generated by Django 5.1.4 on 2025-02-20 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_posting', '0012_alter_applicationtable_interview_frames'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationtable',
            name='confidence_score',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='applicationtable',
            name='face_verification_result',
            field=models.BooleanField(default=True),
        ),
    ]
