# Generated by Django 5.1.4 on 2025-02-21 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job_posting', '0015_applicationtable_face_verification_result'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicationtable',
            name='confidence_score',
        ),
        migrations.RemoveField(
            model_name='applicationtable',
            name='face_verification_result',
        ),
    ]
