# Generated by Django 5.1.4 on 2025-02-21 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_posting', '0016_remove_applicationtable_confidence_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationtable',
            name='confidence_score',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='applicationtable',
            name='face_verification_result',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
