# Generated by Django 5.1.4 on 2025-02-21 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_posting', '0017_applicationtable_confidence_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationtable',
            name='flag_status',
            field=models.BooleanField(default=False),
        ),
    ]
