# Generated by Django 5.1.4 on 2025-03-17 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_posting', '0018_applicationtable_flag_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationtable',
            name='interview_status',
            field=models.CharField(choices=[('not_started', 'Not Started'), ('started', 'Started'), ('completed', 'Completed')], default='not_started', max_length=15),
        ),
    ]
