# Generated by Django 5.1.4 on 2025-03-17 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_posting', '0019_alter_applicationtable_interview_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationtable',
            name='request_interview',
            field=models.BooleanField(default=False),
        ),
    ]
