# Generated by Django 5.1.4 on 2025-03-17 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job_posting', '0020_applicationtable_request_interview'),
    ]

    operations = [
        migrations.RenameField(
            model_name='applicationtable',
            old_name='request_interview',
            new_name='request_re_interview',
        ),
    ]
