# Generated by Django 5.1.4 on 2025-03-19 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_posting', '0021_rename_request_interview_applicationtable_request_re_interview'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationtable',
            name='Interview_logs',
            field=models.JSONField(default=1),
            preserve_default=False,
        ),
    ]
