# Generated by Django 5.1.4 on 2025-03-19 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job_posting', '0022_applicationtable_interview_logs'),
    ]

    operations = [
        migrations.RenameField(
            model_name='applicationtable',
            old_name='Interview_logs',
            new_name='interview_logs',
        ),
    ]
