# Generated by Django 5.1.4 on 2025-03-19 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job_posting', '0023_rename_interview_logs_applicationtable_interview_logs'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='applicationtable',
            unique_together=set(),
        ),
    ]
