# Generated by Django 5.1.4 on 2025-03-19 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_candidatetable_profile_image_and_more'),
        ('job_posting', '0024_alter_applicationtable_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationtable',
            name='interview_logs',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterUniqueTogether(
            name='applicationtable',
            unique_together={('job', 'candidate')},
        ),
    ]
