# Generated by Django 5.1.4 on 2025-05-09 12:11

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job_posting', '0025_alter_applicationtable_interview_logs_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationtable',
            name='resume',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='resume'),
        ),
    ]
